services:
  db:
    env_file: 
        - ./.env
    image: mysql:8.4.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /tmp/code/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    env_file: 
      - ./.env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /tmp/code/mysqld:/run/mysqld
    depends_on:
      - db
